#APP SPECIFIC CUSTOM PROPERTIES
app:
  name: demo
  api:
    title: Spring boot demo API
    version: 1.0.0
    description: Spring boot demo API description
    base-package: com.abc.demo.controller
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
#LOGGING PROPERTIES
logging:
  level:
    root: INFO
#SPRING PROPETIES
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: DB_USER_NAME
    password: ENCRYPTED_PASSWORD
    hikari:      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 10
  # Enabling H2 Console
  h2.console.enabled: true
  jpa:    generate-ddl: false
    show-sql: true